# Generated by Django 3.2.7 on 2021-09-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210926_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Город'),
        ),
    ]
